### ISSUE TITLE
Update title and icon

### ISSUE THREAD

**Issue by GLD5000** [dawkaka/drawapp#19]
Cool app - I saw this on dev.to and noticed the favicon and metadata have not been updated- I am happy to do this for you!
![image](https://github.com/dawkaka/drawapp/assets/33987109/04a268c2-fd88-4030-af39-fbf52aae3d8b)

**Comment by dawkaka** [comment]
That will be great, Thanks.

**Comment by GLD5000** [comment]
Awesome- will do tomorrow!
